###
GET http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo?solYear=2024&solMonth=05&serviceKey=m280WDXwmV3GwL6QGtqK6TlZUEuMl7WUn77RUICcuROP7uLARnESt1NODbsAmK8vkZV%2B8cGkCI5mKB3NOw6pzg%3D%3D
