import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";

import Navigation from "@/components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-[#F2EFE5]">
        <Navigation />
        {children}
      </body>
    </html>
  );
}

// 컴포넌트를 재사용하는 경우 레이아웃 파일을 사용
/* 
넥스트js는 제일 먼저 레이아웃 파일을 읽음-> 그 다음 url 확인해서 그 페이지의 export default 코드를 읽어 실행

'/signin' 페이지로 가는 경우

<RootLayout>
  <SignIn />   <- {children}
</RootLayout>

실제로는 이렇게 렌더링이 됨
*/
